parameters:
#    super_structure.example.class: Tormit\SuperStructureBundle\Example

services:
  superstructure.structure:
    class: Tormit\SuperStructureBundle\EventListener\SuperstructureEvents
    tags:
        - { name: doctrine.event_listener, event: postPersist }
        - { name: doctrine.event_listener, event: postUpdate }
        - { name: doctrine.event_listener, event: postRemove }
