parameters:
#    super_structure.example.class: Tormit\Bundle\SuperStructureBundle\Example

services:
  superstructure.routelistener:
    class:   Tormit\Bundle\SuperStructureBundle\Listener\RouteListener
    tags:
        -  { name: doctrine_mongodb.odm.event_listener, event: postPersist }
        -  { name: doctrine_mongodb.odm.event_listener, event: postRemove }
  superstructure.routing_loader:
        class: Tormit\Bundle\SuperStructureBundle\Routing\SuperStructure
        tags:
            - { name: routing.loader }
  superstructure.twig.extension:
        class: Tormit\Bundle\SuperStructureBundle\Twig\SuperStructureTwigExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }
  superstructure.context:
        class: Tormit\Bundle\SuperStructureBundle\Context\SuperStructureContext
        arguments: [@service_container]
#        tags:
#          - { name: twig.extension }

